### PR TITLE
v4.4.69

### PR DESCRIPTION
**Pull request by stickpin**
**Change log:**

Most of the changes apply to the VW ID models.

- Main Readme update
- Update FlowManager to fulfill the latest Home Assistant requirements (https://developers.home-assistant.io/blog/2024/01/11/async-show-progress-changes/)
- Remove "Requests remaining" sensor. VW Backend no longer returns "Vcf-Remaining-Calls" header for `pendingrequests` API
- Bug fix (https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/589)
- Replace climate control with Switch and Number slider
Screenshot 2024-03-01 at 23 11 38
- Enable Climatisation on ID models.
- Add support for Auxiliary heater in hybrid vehicles
- New Configuration Control: Add Auxiliary heating departure timers
- New Configuration Control: Auto-release AC connector
- New Configuration Control: Automatic window heating
- New Configuration Control: Auxiliary air conditioning
- New Configuration Control: Battery target charge level
- New Configuration Control: Zone Front Left
- New Configuration Control: Zone Right Left
- New Sensor: Electric Remaining Climatisation Time
Screenshot 2024-03-01 at 23 13 22

### CODE REVIEW

**Comment by stickpin** [comment]
@robinostlund Please merge with PR and trigger a new version. The change log in the first comment.
The front end should be merged as well: https://github.com/robinostlund/homeassistant-volkswagencarnet/pull/584

Thanks. :)

**Comment by stickpin** [comment]
@robinostlund if it's ok, please provide me an option to merge PRs myself, so I will stop asking you all the time. :)

**Comment by robinostlund** [comment]
> @robinostlund if it's ok, please provide me permission to merge PRs myself, so I will stop asking you all the time. :)

Which rule prevents you from merge it? :)

**Comment by stickpin** [comment]
@robinostlund I don't know to be completely honest. But I have force merge grayout.
And even when it passes all the pre-requisite tests, it still requires one review.

**Pull request merged**
