### PR TITLE
Re-enable controls

### PR DESCRIPTION
**Pull request by oliverrahner**
Re-implementation of the controls

### CODE REVIEW

**Comment by stickpin** [comment]
@oliverrahner I am unsure if I understand the difference between "Auxiliary Climatisation" and "Electric Climatisation".
I am working with PHEV Tiguan now and in the original VW app you can enable Auxiliary Climatisation in the settings but not as an On/Off switch. Do you know the difference? :)

I will stop working on rest climatization functionality until I understand the logic. Maybe EV acts differently, but I don't have access to one.

I will focus on re-enabling Horn & Turn Signals.

In any case, it's Christmas/New Year time now, so not sure how much time I will have to work on it in the next two weeks.
Maybe it makes sense to release a new Beta with those two switches enabled, to collect some feedback from other users.

**Comment by oliverrahner** [comment]
I don't know the difference either :-/ I hoped it would get clearer with access to more different vehicles, but I haven't found the meaning yet, and if they are mutually exclusive or might be part of the same car.

@robinostlund could you create a beta from this branch?

I'll be on holiday for a week now, with little to no time to work on this.

Wish you all a Happy Christmas :)

**Comment by robinostlund** [comment]
> I don't know the difference either :-/ I hoped it would get clearer with access to more different vehicles, but I haven't found the meaning yet, and if they are mutually exclusive or might be part of the same car.
> 
> @robinostlund could you create a beta from this branch?
> 
> I'll be on holiday for a week now, with little to no time to work on this.
> 
> Wish you all a Happy Christmas :)

Sure will release a new beta version 😄  thank you for all your help and have an awesome christmas 🎅

**Comment by ilkkasaa** [comment]
>I am unsure if I understand the difference between "Auxiliary Climatisation" and "Electric Climatisation".

Is "Auxiliary Climatisation" same thing as "Auxiliary heater"?

In my Arteon PHEV there are following settings in the Volkswagen app's Air Conditioning settings: 
photo_2023-12-22_09-53-15

Auxiliary heater is the one that only heats and runs on gasoline instead of electricity.

**Comment by mrandt** [comment]
Just to second what @ilkkasaa commented re the "auxiliary" heater:

The auxiliary heater is a gasoline powered heater which had to be ordered as an add-on (about 1.000 €). I believe it is made by Webasto. Naturally, it is only an option in PHEV.

I have a Passat B6 GTE PHEV (Model Type C3) in Germany and made the mistake of ordering that extra. As the car supports electric climatization (from charger or battery) I hardly ever use the auxiliary heater.

I took a screenshot from German Volkswagen app - here it is labeled "Standheizung":

image

IMHO the terms are also a bit misleading; as climatization (electric) also includes heating or cooling (depending on outside temperature).

**Comment by oliverrahner** [comment]
Thanks for the input. That should enable us to implement the features accordingly. We only need to check if these features are available in the accounts we have available in the meantime 😅

**Comment by stickpin** [comment]
Hi @robinostlund,

Please trigger a new beta.
_Change log:_
- Fix Last connected sensor
- New Last Data refresh sensor 
- Code Clean-up 
- Re-introduce Force Data Refresh
- Increase wait intervals to 10 seconds to reduce server hammering 

Thanks! :)

**Comment by robinostlund** [comment]
> Hi @robinostlund,
> 
> Please trigger a new beta. _Change log:_
> 
> * Fix Last connected sensor
> * New Last Data refresh sensor
> * Code Clean-up
> * Re-introduce Force Data Refresh
> * Increase wait intervals to 10 seconds to reduce server hammering
> 
> Thanks! :)

Lovely, new beta is released now 😄

**Comment by stickpin** [comment]
Hi @robinostlund,

Please trigger a new beta.
Change log:
- Initial VW ID models support (Tested with ID3 - Thanks to @OZ1SEJ for access to the vehicle!)

Thanks! :)

**Comment by robinostlund** [comment]
@stickpin new beta released 😄

**Comment by stickpin** [comment]
Change log for the upcoming beta:
- Fix issue #243 
- Small code fixes
- Add Rear Sunroof sensor for compatible vehicles
- Add Charging rate sensor for compatible vehicles
- Add Charging power sensor for compatible vehicles

**Comment by stickpin** [comment]
Hi @robinostlund,

Please trigger a new beta.
The changes are mostly related to VW EVs.

Change log:
- Fix issue #243 
- Small code fixes
- Add Rear Sunroof sensor for compatible vehicles
- Add Charging rate sensor for compatible vehicles
- Add Charging power sensor for compatible vehicles
- Add Charger type sensor for compatible vehicles
- Add Battery target charge level sensor for compatible vehicles

FYI @oliverrahner

**Comment by robinostlund** [comment]
@stickpin @oliverrahner maby we should merge this PR to master and then work on multiple PR for each feature? Whats your thought about that? 😄

**Comment by stickpin** [comment]
@robinostlund I agree... It seems to be also a bit more complicated than I was thinking from the beginning. 
That's why I've disabled the Window Heater switch as well for the time being. We need to invest more time in vehicle "feature" detection.

@oliverrahner what is your view?

**Comment by oliverrahner** [comment]
@stickpin @robinostlund I agree to the proposal. Honestly, I wasn't following the commits very much over the past weeks 😅 The goal should be that master is usually representing the latest release state.
Additional work should then be done in PRs, potentially creating beta releases from specific PRs if necessary.

I would do it that way, unless you have something else on your mind @robinostlund

**Comment by robinostlund** [comment]
@oliverrahner @stickpin lets start with multiple PR and merge this one to master, @stickpin anything you wan't to commit before i merge this request and release a new version? 😄

**Comment by stickpin** [comment]
@robinostlund no, I don't have anything new yet. 😀 we can merge. :)

**Pull request merged**
