### PR TITLE
Add pre-commit dependency and configuration

### PR DESCRIPTION
**Pull request by milkboy**

### CODE REVIEW

**Comment by milkboy** [comment]
image
:heart:

**Comment by robinostlund** [comment]
LOVELY ❤️

**Comment by milkboy** [comment]
> LOVELY heart

Got annoyed by actions failing after some tiny change. So this should help in avoiding those annoyances (well, the docstrings might take a while to iron out completely)

**Review by robinostlund — APPROVED** [review]

**Comment by milkboy** [comment]
oh, one more thing.. how should the pre-commit repository versions be handled? There seems to be a couple of ways:
- manual (running `pre-commit autoupdate`)
- using renovate bot (well, we have dependabot, so... :shrug: )
- using an action in Github
- using https://pre-commit.ci/

**Comment by robinostlund** [comment]
Good question, i havent used pre-commit before, what do you say? maby we should test the different ways? :)

**Comment by milkboy** [comment]
There's a first time for everything :D Never used it before either, but know several projects that have good experience with it. Definitely simplifies and visualizes things nicely. Would maybe try the pre-commit.ci approach to see if it's any good. As a bonus, it should (by default at least) autofix any new PRs in the same way as the local git hook if I understood it correctly.

**Pull request merged**
