### PR TITLE
Draft: add sunroof sensor

### PR DESCRIPTION
**Pull request by David-Development**
Needed for https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/181

### CODE REVIEW

**Comment by David-Development** [comment]
@robinostlund One question.. When I try setting up the home-assistant integration, I'm getting the following error message. Do you know what might cause it? 

```
...
home-assistant_1  | 2020-08-13 20:31:22 DEBUG (MainThread) [dashboard] XXX Last trip total electric consumption (Sensor:trip_last_total_electric_consumption) is not supported
home-assistant_1  | 2020-08-13 20:31:22 DEBUG (MainThread) [dashboard] XXX External power is supported
home-assistant_1  | 2020-08-13 20:31:22 DEBUG (MainThread) [dashboard] XXX Parking light is supported
home-assistant_1  | 2020-08-13 20:31:22 DEBUG (MainThread) [dashboard] XXX Climatisation without external power is supported
home-assistant_1  | 2020-08-13 20:31:22 DEBUG (MainThread) [dashboard] XXX Doors locked is supported
home-assistant_1  | 2020-08-13 20:31:22 DEBUG (MainThread) [dashboard] XXX Trunk locked is supported
home-assistant_1  | 2020-08-13 20:31:22 DEBUG (MainThread) [dashboard] XXX Windows closed is supported
home-assistant_1  | 2020-08-13 20:31:22 DEBUG (MainThread) [dashboard] XXX Window closed left front is supported
home-assistant_1  | 2020-08-13 20:31:22 DEBUG (MainThread) [dashboard] XXX Window closed left back is supported
home-assistant_1  | 2020-08-13 20:31:22 DEBUG (MainThread) [dashboard] XXX Window closed right front is supported
home-assistant_1  | 2020-08-13 20:31:22 DEBUG (MainThread) [dashboard] XXX Window closed right back is supported
home-assistant_1  | 2020-08-13 20:31:22 INFO (SyncWorker_12) [homeassistant.loader] Loaded lock from homeassistant.components.lock
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.device_tracker: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.switch: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.switch: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.climate: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.switch: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.switch: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.binary_sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.binary_sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.binary_sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.binary_sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.binary_sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.binary_sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.binary_sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.binary_sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.binary_sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.binary_sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.binary_sensor: Unable to set up component.
home-assistant_1  | 2020-08-13 20:31:22 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagencarnet.binary_sensor: Unable to set up component.
```

**Comment by robinostlund** [comment]
What happens if you run python volkswagecarnet.py ?

**Comment by David-Development** [comment]
@robinostlund It prints out the identifier of the car. I also tested the sample you provided in the readme and it works perfectly fine and it prints out all the sensors (including the sunroof that I've added). I just can't get it working inside home-assistant 😅  

I had the same error messages when I tried setting it up by downloading the hacs plugin inside home assistant. Not sure whats going wrong along the way.

**Comment by robinostlund** [comment]
Oright, could it be issues with we connect? it gives strange errors in that case :) in which country are you located? As this plugin is only working for europe.

**Comment by David-Development** [comment]
Great, thank you! :) I'm located in Germany and I can use the app without any problems. If I run the example code from this repo, I can see all my car details as well. I'll try investigating more this afternoon

**Comment by David-Development** [comment]
@robinostlund After upgrading my home assistant to 0.114.0 it works now 🎉 Thank you!

**Pull request merged**
