### PR TITLE
v4.4.66

### PR DESCRIPTION
**Pull request by stickpin**
Change log:
- One more attempt to fix the last connected sensor logic (https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/569)
- Change charging_time_left sensor logic (https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/572)
- Implementation of Electric climatisation controls with temperature (https://github.com/robinostlund/homeassistant-volkswagencarnet/pull/573)
Screenshot 2024-02-17 at 11 10 39
- Change actions processing logic to use new `pendingrequests` API
- Small typos and bug fixes
- Add Reduced AC charging control and rename "Charger max" sensors.

**Reduced AC charging ON:**
Screenshot 2024-02-18 at 13 56 31
Screenshot 2024-02-18 at 13 56 55

**Reduced AC charging OFF:**
Screenshot 2024-02-18 at 13 58 23
Screenshot 2024-02-18 at 13 58 46

### CODE REVIEW

**Comment by stickpin** [comment]
Hi @robinostlund,

I am stuck a bit with the climatisation control implementation on the temperature control on "frontend" side, can you please take a look at my question here: https://github.com/robinostlund/homeassistant-volkswagencarnet/discussions/568
Backend-side logic is already done.

Thanks.

**Comment by stickpin** [comment]
Hi @robinostlund,

Please merge this PR and trigger an official/final version.
This version requires merging the frontend changes as well: https://github.com/robinostlund/homeassistant-volkswagencarnet/pull/574
The full Change log in the initial comment. 
The most important change is the use of the newly introduced `pendingrequests` API which should increase the integration actions reliability.

Thanks! :)

FYI @oliverrahner

**Comment by stickpin** [comment]
@robinostlund please hold on, found some bug with ID3. I will inform you once it's solved.

**Comment by stickpin** [comment]
@robinostlund now we are good to go.
Tested with 8 different vehicles.
Screenshot 2024-02-18 at 14 59 46

**Comment by robinostlund** [comment]
Awesome work @stickpin, new version released now 😄

**Pull request merged**
