### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by milkboy**
Initial commits for more tests. Mostly for checking how to actually do testing, and checking the build pipeline.

Relates to #163, but still needs _loads_ of work.

Also generates html output reports (not sure if it brings any added value to have those by default though?)

Sample pytest run output
image

image

image

### CODE REVIEW

**Comment by milkboy** [comment]
As expected. Something blew up in the actions :smile:

**Comment by milkboy** [comment]
@robinostlund how would you btw feel about dropping Python 3.6 support, as it's EOL already?

**Comment by robinostlund** [comment]
> @robinostlund how would you btw feel about dropping Python 3.6 support, as it's EOL already?

Totally up for it 😊 lets drop 3.6 🥳

**Comment by robinostlund** [comment]
Removed 3.6 check now as an requirement 😊

**Comment by milkboy** [comment]
Would it be possible to add this to the PR pipeline also? https://about.codecov.io/blog/python-code-coverage-using-github-actions-and-codecov/
It looks like it's pretty simple; only the API token needs to be configured in addition to the new steps

**Comment by robinostlund** [comment]
> Would it be possible to add this to the PR pipeline also? https://about.codecov.io/blog/python-code-coverage-using-github-actions-and-codecov/ It looks like it's pretty simple; only the API token needs to be configured in addition to the new steps

it is now added, but not an requirement yet as it needs to be configured more, do you have time to look at it? :)
I think you should be able to release new versions of the library, do you have the publlish possibilities on the draf release?

**Comment by robinostlund** [comment]
Is this pr ready for merge btw @milkboy ? :)

**Comment by milkboy** [comment]
I'll add a couple of commits that are "99% done"

**Comment by milkboy** [comment]
Oh, and now there is a new button "draft release", which was definitely not there before 🪄

**Comment by robinostlund** [comment]
> Oh, and now there is a new button "draft release", which was definitely not there before 🪄

yeah :) think you get it how it works :) pre = test, and when you publish the real shit it builds package to pypi, and tomorrow ha-volkswagencarnet will have a new pr with the new version triggered by dependabot :)

**Comment by milkboy** [comment]
> > Oh, and now there is a new button "draft release", which was definitely not there before magic_wand
> 
> yeah :) think you get it how it works :) pre = test, and when you publish the real shit it builds package to pypi, and tomorrow ha-volkswagencarnet will have a new pr with the new version triggered by dependabot :)

Sounds too simple :wink:

**Comment by milkboy** [comment]
okay. looks like "something" is working, regarding code coverage. might need more tweaking to be perfect, but this looks like a fine start at least :smiley: 

now I'll stop editing this PR. any further changes will get a new one

**Comment by robinostlund** [comment]
I leave the merge and release to you then 🥳🥳

**Comment by milkboy** [comment]
> I leave the merge and release to you then partying_facepartying_face

oh oh

**Pull request merged**
