### PR TITLE
Sensor 'Charging time left' as number of minutes

### PR DESCRIPTION
**Pull request by koleo9am**
Integration to Home Assistant has problem with string representation of "Charging time left".
So I changed the value to integer and defined the unit.

### CODE REVIEW

**Comment by koleo9am** [comment]
@robinostlund can I ask for processing this PR. Reject or accept, please.

**Comment by robinostlund** [comment]
@koleo9am sorry missed this PR, thanks for your help 😄

**Comment by koleo9am** [comment]
Thank You very much. Can I ask You for a release of volkswagencarnet and also homeassistant-volkswagencarnet?
I can help with the homeassistant-volkswagencarnet bump up.

**Comment by opsiorobinostlund** [comment]
@koleo9am dependabot should find a new version of it tomorrow and automatically create a PR for it 😄

**Comment by robinostlund** [comment]
@koleo9am dependabot should find a new version of it tomorrow and automatically create a PR for it 😄

**Pull request merged**
