### PR TITLE
Rewrite the authentication dance password submission part

### LINKED ISSUE #137: login failed
Hey folks

Today the login crashed with the following error:
**DEBUG:vw_connection:Using service https://msg.volkswagen.de
DEBUG:vw_connection:Initiating new login
DEBUG:vw_connection:Got authorization endpoint
ERROR:vw_connection:Failed to extract password login form.
ERROR:vw_connection:Login failed for VW account, 'NoneType' object has no attribute 'find_all'
ERROR:vw_connection:'NoneType' object has no attribute 'find_all'
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/vw_connection.py", line 254, in _login
    raise e
  File "/home/pi/.local/lib/python3.7/site-packages/vw_connection.py", line 249, in _login
    response_soup.find('form', id='credentialsForm').find_all('input', type='hidden')])
AttributeError: 'NoneType' object has no attribute 'find_all'
INFO:vw_connection:Something failed**

A friend got the same messages. Does anybody else has such problems? The response from the server seems some how currupted.

### PR DESCRIPTION
**Pull request by milkboy**
Fixes for server side changes

Fixes #137

### CODE REVIEW

**Comment by milkboy** [comment]
Tested locally with my actual username and password, and it passed.

**Comment by tubalainen** [comment]
Issues with SPIN - please await fix until merge.

**Comment by milkboy** [comment]
> Issues with SPIN - please await fix until merge.

Guessing that's actually a different issue though? With failing login, the API is completely unusable

**Comment by tubalainen** [comment]
@robinostlund your call - the login and all non-SPIN features work with this PR. 
Release or fix "all" then release?

**Review by robinostlund — APPROVED** [review]
Thanks for your help!

**Pull request merged**
