### PR TITLE
Test updates

### PR DESCRIPTION
**Pull request by milkboy**
Separate test dependencies to requirements-test.txt, to avoid requiring them in dependent projects.
Add a real login test (that should succeed, if working username and password is specified, otherwise test is skipped)

### CODE REVIEW

**Comment by milkboy** [comment]
Oh, and should prevent the issue mentioned in https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/354

**Review by robinostlund — APPROVED** [review]
Looks good, thanks for you help 😊

**Comment by milkboy** [comment]
Ah, the 3.6 build is required.. will add that back then for now

**Review by robinostlund — APPROVED** [review]

**Comment by robinostlund** [comment]
@milkboy ready for merge? 😊

**Comment by milkboy** [comment]
> @milkboy ready for merge? 😊

Yea

**Pull request merged**
