### PR TITLE
Implements a new Mobile API

### PR DESCRIPTION
**Pull request by JohNan**
I took all code from https://github.com/lendy007/skodaconnect and modified it a bit to work with VW. It does however require some modification in the HA integration also: https://github.com/robinostlund/homeassistant-volkswagencarnet/pull/277. This should fix https://github.com/robinostlund/volkswagencarnet/issues/111 but we probably need som beta testing before we can make a release of it.

### CODE REVIEW

**Comment by robinostlund** [comment]
@JohNan we can release a pre release on the ha integration maby?

**Comment by JohNan** [comment]
@robinostlund sounds good, and make a real release of the api module. 

We still need to bump the version of the api module before we merge this.

**Comment by isabellaalstrom** [comment]
Awesome. I'm open for beta testing

**Comment by JohNan** [comment]
There's an issue with the package name when loaded into HA. It worked in my dev env but not when adding the dist file with pip. It cannot find the module named `volkswagencarnet` for some reason.

Packaging is not my strongest side, @robinostlund are you able to help?

**Comment by JohNan** [comment]
looks like it collided with custom component name itself or something. I renamed the package to `vwweconnect` and it was picked up correctly. @robinostlund how would you suggest that we do? Skip module name completly (like before) or rename it?

**Comment by Farfar** [comment]
Nice to get a mention since most of the code is our work ;)

**Comment by JohNan** [comment]
> Nice to get a mention for our work ;)

It's a full circle since your repo is a fork of this repo 😁

**Comment by Farfar** [comment]
> It's a full circle since your repo is a fork of this repo 😁

Haha yes indeed 😄



> I think we can share quite a lot between the repos since there are many similarities

I will borrow the config flow! 😘

For the library, the base functions should be the same though I think Skoda is moving towards their own API. At least it seems that way when I've inspected traffic for Skoda Enyaq iV. I wouldn't be surprised if VWs new electrics are using new endpoints that the current implementation hasn't covered.
Login and token handling seems to be the same for all VAG brands though, Seat was a simple fix to get working from Skodaconnect code. That's why the code should have been fairly easy to modify for VW.

**Pull request merged**
