### PR TITLE
v4.4.68

### PR DESCRIPTION
**Pull request by stickpin**
**Change Log:**
- Code clean-up
- New Sensor: Car Type
- New Sensor: Battery cruising range
- New Sensor: Auxiliary remaining climatisation time
- Add additional missing status (cooling) to Electric Climatisation
- Fix bug when the electric climatisation status was not reflected in the Home Assistant
- Re-implementation of the Auxiliary Heater switch.
- Fix Electric range sensor edge case (https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/582)
- Introduction of the new Departure Timers logic. Previous Departure Timers functionality is deprecated due to incompatibility with the new VW Backend.
Screenshot 2024-02-21 at 11 55 25
Screenshot 2024-02-21 at 11 54 55
Screenshot 2024-02-21 at 11 01 41

### CODE REVIEW

**Comment by stickpin** [comment]
@robinostlund a new day a new version. 🤣

Please trigger a new version, should come together with the frontend changes: https://github.com/robinostlund/homeassistant-volkswagencarnet/pull/579

The change log is in the initial comment. 

Thanks! 😊

**Comment by stickpin** [comment]
@robinostlund any chance you can merge and release a new version?

**Comment by stickpin** [comment]
@robinostlund we are good to go now. :)

**Comment by robinostlund** [comment]
@stickpin i'm out travelling for a while, if you wan't you can try to release it by yourself :) everything is managed in github workflows so it should be easy for you :smile:

**Comment by stickpin** [comment]
Hi @robinostlund,
The problem is that I cannot force merge it myself unless I am missing something:
Screenshot 2024-02-24 at 14 20 25

**Comment by robinostlund** [comment]
@stickpin ahaa oright, i can override. Is it ready for merge? 😊

**Comment by stickpin** [comment]
@robinostlund right in time! :) Just finished Auxiliary Heater implementation. 😊
Please merge both this PR and the frontend part: https://github.com/robinostlund/homeassistant-volkswagencarnet/pull/579

**Pull request merged**
